### ISSUE TITLE
image processing : unable to open file

### ISSUE THREAD

**Issue by aayushsinghm16** [VeliovGroup/Meteor-Files-Demo#1]
`W20170823-18:26:18.635(5.5)? (STDERR) [createThumbnails] [img.resize] { [Error: Command failed: gm convert: Unable to open file (assets\app\uploads\images\YTWpDndzksMdtKK6Q.jpg) [No such file or directory].
W20170823-18:26:18.636(5.5)? (STDERR) ] code: 1, signal: null }
I20170823-18:26:18.637(5.5)? file
W20170823-18:26:18.637(5.5)? (STDERR) { [Error: Command failed: gm convert: Unable to open file (assets\app\uploads\images\YTWpDndzksMdtKK6Q.jpg) [No such file or directory].
W20170823-18:26:18.638(5.5)? (STDERR) ] code: 1, signal: null }`

this is the error i am getting with gm , i m using gridfs for file storage

**Comment by dr-dimitru** [comment]
Well, file is obviously is moved to GridFS, and not exists on your FS.
You should run `gm` over the file before moving it to GridFS

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.

**Comment by aayushsinghm16** [comment]
problem was
```js
uploadsCollection.on('afterUpload', function(fileRef) {
  // Run `createThumbnails` only over PNG, JPG and JPEG files
  if (/png|jpe?g/i.test(fileRef.extension || '')) {
    createThumbnails(this, fileRef, (error, fileRef) => {
      if (error) {
        console.error(error);
      }
    });
  }
});
```

here fileRef, don't have thumbnail info, for gridfs, i have to create a new reference by calling 

```js
var ref=this.collection.findOne(fileRef._id);

Object.keys(ref.versions).forEach(versionName => {
    console.log(versionName);
    const metadata = { versionName, imageId: ref._id, storedAt: new Date() }; // Optional
    const writeStream = gfs.createWriteStream({ filename: ref.name, metadata });
    fs.createReadStream(ref.versions[versionName].path).pipe(writeStream);
    writeStream.on('close', Meteor.bindEnvironment(file => {
      const property = `versions.${versionName}.meta.gridFsFileId`;

      // If we store the ObjectID itself, Meteor (EJSON?) seems to convert it to a
      // LocalCollection.ObjectID, which GFS doesn't understand.
      this.collection.update(ref._id, { $set: { [property]: file._id.toString() } });
      this.unlink(this.collection.findOne(ref._id), versionName); // Unlink files from FS
    }));
  });
```

**Comment by dr-dimitru** [comment]
@aayushsinghm16 you're right.

Please consider to read this *FYI*:
 - https://guides.github.com/features/mastering-markdown/
 - https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

**Comment by aayushsinghm16** [comment]
@dr-dimitru thanks
